apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: fucking-kubectl-ci-pr-
  namespace: ci
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && (body.action == "opened" || body.action == "reopened" || body.action == "synchronize" || body.action == "ready_for_review") && body.pull_request.base.ref == "main" && body.pull_request.draft == false
    pipelinesascode.tekton.dev/max-keep-runs: "10"
spec:
  taskRunTemplate:
    serviceAccountName: tekton-runner
  pipelineRef:
    resolver: git
    params:
      - name: org
        value: paulharkink
      - name: repo
        value: fucking-kubectl
      - name: revision
        value: "{{ revision }}"
      - name: pathInRepo
        value: .tekton/ci-shared-pipeline.yaml
      - name: token
        value: ci-pac-github-provider
      - name: tokenKey
        value: token
      - name: scmType
        value: github
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: source_branch
      value: "{{ source_branch }}"
    - name: target_branch
      value: "{{ target_branch }}"
    - name: mode
      value: pr
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
